spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prueba
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: n.times000@gmail.com
    password: springboot
    port: 587
    debug: true
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000